In [4]:
import pandas as pd
import numpy as np

from google.colab import files

# Upload dataset
uploaded = files.upload()

# Read uploaded CSV
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)

print("Dataset loaded successfully!")
print(df.head())

Saving messy_student_data (1).csv to messy_student_data (1).csv
Dataset loaded successfully!
   Student_ID    Name  Age  Gender        City Score Department
0           1  Ananya   20  Female   Bengaluru    85        CSE
1           2   Rahul  NaN       M   Bangalore    78        ISE
2           3   Sneha   21  female      Mysore   NaN        ECE
3           4   Kiran   22    Male      Mysuru    91        CSE
4           5   Priya   20       F  Bengaluru     88        ISE

In [5]:
# ==========================================
# TASK 1: DATA CLEANING & PREPROCESSING
# ==========================================

# 1. Inspect dataset structure

print("Dataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

print("\nFirst 5 Rows:")
display(df.head())

# 2. Identify missing values

print("\nMissing Values:")
print(df.isnull().sum())

# 3. Identify duplicate records

print("\nDuplicate Records:")
print(df.duplicated().sum())

# 4. Display statistical summary

print("\nStatistical Summary:")
display(df.describe(include="all"))

Dataset Shape:
(12, 7)

Column Names:
['Student_ID', 'Name', 'Age', 'Gender', 'City', 'Score', 'Department']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  12 non-null     int64
 1   Name        12 non-null     object
 2   Age         11 non-null     object
 3   Gender      11 non-null     object
 4   City        11 non-null     object
 5   Score       11 non-null     object
 6   Department  12 non-null     object
dtypes: int64(1), object(6)
memory usage: 804.0+ bytes

First 5 Rows:

   Student_ID    Name  Age  Gender        City Score Department
0           1  Ananya   20  Female   Bengaluru    85        CSE
1           2   Rahul  NaN       M   Bangalore    78        ISE
2           3   Sneha   21  female      Mysore   NaN        ECE
3           4   Kiran   22    Male      Mysuru    91        CSE
4           5   Priya   20       F  Bengaluru     88        ISE

Missing Values:
Student_ID    0
Name          0
Age           1
Gender        1
City          1
Score         1
Department    0
dtype: int64

Duplicate Records:
1

Statistical Summary:

        Student_ID   Name  Age  Gender       City Score Department
count    12.000000     12   11      11         11    11         12
unique         NaN     11    5       6          5    10          3
top            NaN  Rohan   20  Female  Bangalore    77        CSE
freq           NaN      2    3       3          3     2          4
mean      6.333333    NaN  NaN     NaN        NaN   NaN        NaN
std       3.366502    NaN  NaN     NaN        NaN   NaN        NaN
min       1.000000    NaN  NaN     NaN        NaN   NaN        NaN
25%       3.750000    NaN  NaN     NaN        NaN   NaN        NaN
50%       6.500000    NaN  NaN     NaN        NaN   NaN        NaN
75%       9.250000    NaN  NaN     NaN        NaN   NaN        NaN
max      11.000000    NaN  NaN     NaN        NaN   NaN        NaN

In [6]:
# ==========================================
# DATA CLEANING
# ==========================================

# Make a copy of the dataset
cleaned_df = df.copy()

# 1. Remove duplicate records

cleaned_df = cleaned_df.drop_duplicates()

# 2. Handle missing values

for column in cleaned_df.columns:

    if cleaned_df[column].dtype == "object":

        cleaned_df[column] = cleaned_df[column].fillna(
            cleaned_df[column].mode()[0]
        )

    else:

        cleaned_df[column] = cleaned_df[column].fillna(
            cleaned_df[column].median()
        )

# 3. Remove extra spaces from text columns

for column in cleaned_df.select_dtypes(include="object").columns:

    cleaned_df[column] = cleaned_df[column].str.strip()

# 4. Display cleaned dataset

print("Cleaned Dataset:")
display(cleaned_df.head())

# 5. Check missing values after cleaning

print("\nMissing Values After Cleaning:")
print(cleaned_df.isnull().sum())

# 6. Check duplicate records after cleaning

print("\nDuplicate Records After Cleaning:")
print(cleaned_df.duplicated().sum())

Cleaned Dataset:

   Student_ID    Name Age  Gender       City Score Department
0           1  Ananya  20  Female  Bengaluru    85        CSE
1           2   Rahul  20       M  Bangalore    78        ISE
2           3   Sneha  21  female     Mysore    69        ECE
3           4   Kiran  22    Male     Mysuru    91        CSE
4           5   Priya  20       F  Bengaluru    88        ISE

Missing Values After Cleaning:
Student_ID    0
Name          0
Age           0
Gender        0
City          0
Score         0
Department    0
dtype: int64

Duplicate Records After Cleaning:
0

In [7]:
# ==========================================
# COMPLETE DATA CLEANING
# ==========================================

# Create a copy of the original dataset
cleaned_df = df.copy()

# 1. Remove duplicate records
cleaned_df = cleaned_df.drop_duplicates()

# 2. Remove extra spaces from text columns
for column in cleaned_df.select_dtypes(include="object").columns:
    cleaned_df[column] = cleaned_df[column].str.strip()

# 3. Standardize Gender values
cleaned_df["Gender"] = (
    cleaned_df["Gender"]
    .astype("string")
    .str.lower()
    .replace({
        "m": "Male",
        "male": "Male",
        "f": "Female",
        "female": "Female"
    })
)

# 4. Standardize City values
cleaned_df["City"] = (
    cleaned_df["City"]
    .astype("string")
    .str.lower()
    .replace({
        "bangalore": "Bengaluru",
        "mysore": "Mysuru"
    })
)

# 5. Convert Age and Score to numeric
cleaned_df["Age"] = pd.to_numeric(
    cleaned_df["Age"], errors="coerce"
)

cleaned_df["Score"] = pd.to_numeric(
    cleaned_df["Score"], errors="coerce"
)

# 6. Handle missing values
cleaned_df["Age"] = cleaned_df["Age"].fillna(
    cleaned_df["Age"].median()
)

cleaned_df["Score"] = cleaned_df["Score"].fillna(
    cleaned_df["Score"].median()
)

cleaned_df["Gender"] = cleaned_df["Gender"].fillna(
    cleaned_df["Gender"].mode()[0]
)

cleaned_df["City"] = cleaned_df["City"].fillna(
    cleaned_df["City"].mode()[0]
)

# 7. Display cleaned dataset
print("CLEANED DATASET")
display(cleaned_df)

# 8. Check remaining missing values
print("\nMissing Values After Cleaning:")
print(cleaned_df.isnull().sum())

# 9. Check duplicate records
print("\nDuplicate Records After Cleaning:")
print(cleaned_df.duplicated().sum())

CLEANED DATASET

    Student_ID    Name   Age  Gender       City  Score Department
0            1  Ananya  20.0  Female  bengaluru   85.0        CSE
1            2   Rahul  21.0    Male  Bengaluru   78.0        ISE
2            3   Sneha  21.0  Female     Mysuru   82.0        ECE
3            4   Kiran  22.0    Male     mysuru   91.0        CSE
4            5   Priya  20.0  Female  bengaluru   88.0        ISE
5            6   Arjun  21.0    Male  Bengaluru   75.0        ECE
6            7   Divya  21.0  Female  bengaluru   82.0        CSE
7            8  Vikram  23.0    Male  Bengaluru   69.0        ISE
8            9   Megha  20.0  Female     Mysuru   95.0        CSE
9           10   Rohan  22.0    Male     mysuru   77.0        ECE
11          11   Pooja  21.0  Female  Bengaluru   82.0        ISE

Missing Values After Cleaning:
Student_ID    0
Name          0
Age           0
Gender        0
City          0
Score         0
Department    0
dtype: int64

Duplicate Records After Cleaning:
0

In [11]:
# Save the final cleaned dataset

cleaned_df.to_csv("cleaned_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [12]:
from google.colab import files

files.download("cleaned_dataset.csv")